CREATE TABLE IF NOT EXISTS public.register(
    -- AUTO INCREMENTE
    id SERIAL PRIMARY KEY,
    --LES CHAMPS DU FORMULAIRE
    nom VARCHAR(50) NOT NULL, 
    prenom VARCHAR(50) NOT NULL, 
    email VARCHAR(50) UNIQUE,   
    tel VARCHAR(15) UNIQUE,
    mdp  TEXT NOT NULL,
    term BOOLEAN,
    --DATE DE CREATION AUTOMATIQUE 
    created_at TIMESTAMP DEFAULT NOW(),
    --DATE DE MIS A JOUR
    updated_at TIMESTAMP DEFAULT NOW() 
);
